config/routes.rb
Rails.application.routes.draw do
  get 'product/index'
  get 'product/show'
  devise_for :users
  root to: 'pages#home'
  resources :products, :productors, only: [:index, :show]
  resources :orders, only: [:create, :index, :show] do
    resources :payments, only: [:new, :create]
  end
  resources :order_products, only: [:index, :create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  acts_as :user
  has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_products, dependent: :destroy
  enum status: {pending: 0, paid:1}

  def amount_update
    amount_cents = self.order_products.map{|op| op.quantity * op.price_cents}.reduce(:+)
    amount_cents = 0 if amount_cents.nil?
    self.update(amount_cents: amount_cents)
  end

  def amount_create
    a = self.order_products.map{|op| op.quantity * op.price_cents}.reduce(:+)
    self.amount_cents = a
  end

  def order_products?
    self.order_products.present?
  end

  monetize :amount_cents
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :product, presence: true
  validates :order, presence: true
  monetize :price_cents
  # before_save :finalize

  # def total_price
  #   price * quantity
  # end

  # private

  # def finalize
  #   self[:unit_price] = unit_price
  #   self[:total_price] = quantity * self[:unit_price]
  # end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :productor
  has_many :order_products, dependent: :destroy
  monetize :price_cents

end

app/models/productor.rb
class Productor < ApplicationRecord
  acts_as :user
  has_many :products, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  actable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_order


  def current_order
    if user_signed_in?
      if session[:order_id].present? && Order.find(session[:order_id]).status == "pending"
        order ||= Order.find(session[:order_id])
        return order
      else
        order = Order.create(customer: current_user.specific)
        session[:order_id] = order.id
        return order
      end
    end
  end

  def configure_permitted_parameters
    user_data = [
      :first_name,
      :last_name,
      :address,
      :phone,
      :siret,
      :compagny,
      :email,
      :password,
      :actable_id,
      :actable_type
    ]

    devise_parameter_sanitizer.permit(:sign_up, keys: user_data)
    devise_parameter_sanitizer.permit(:account_update, keys: user_data)
  end

end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = current_order
    @order_products = current_order.order_products
  end
end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  before_action :authenticate_user!
  def index
    @order_products = OrderProduct.where(order: current_order)
    @order = current_order
  end

  def create
    @product = Product.find(params[:format])
    
    @order_product = current_order.order_products.find_or_create_by(product: @product)

    @order_product.quantity.nil? ? @order_product.quantity = 1 : @order_product.quantity += 1

    @order_product.price = @product.price
    @order_product.save
    current_order.amount_update
  end

  def update
    @order = current_order
    @order_product = @order.order_products.find(params[:id])
    @order_product.update_attributes(order_product_params)
    @order.amount_update
    @order_products = @order.order_products
  end

  def destroy
    @order = current_order
    @order_product = @order.order_products.find(params[:id])
    @order_product.destroy
    @order.amount_update
    redirect_to order_products_path

  end

  private
  def order_product_params
    params.require(:order_product).permit(:quantity, :product_id, :price, :order_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = Order.where(customer: current_user.specific, status: "paid")
  end

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end


  def create
    # customer = current_user
    # order_products = current_order.order_products
    # order  = Order.create!(amount: teddy.price, user: current_user)
    redirect_to new_order_payment_path(current_order)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.all
    @productors = Productor.all
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
  end

  def create
    @order.paid!
    redirect_to order_path(@order)
  end

private

  def set_order
    @order = current_order
  end
end

app/controllers/productors_controller.rb
class ProductorsController < ApplicationController
  def index
    @productors = Productor.all
  end

  def show
    @productor = Productor.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def index
    @products = Product.all
    @order_product = current_order.order_products.new
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Perigord</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/order_products/create.js.erb
$(".count").removeClass('d-none')
$(".cart-number").html("<%= current_order.order_products.count %>")

app/views/order_products/destroy.html.erb
<h1>OrderProducts#destroy</h1>
<p>Find me in app/views/order_products/destroy.html.erb</p>

app/views/order_products/index.html.erb
<div class="container">
  <div class="order-container">
    <h1 class="text-center title-home my-4">Votre Panier</h1>

    <% @order_products.each_with_index do |op, index| %>
      <div class="command-slats d-flex">

        <div class="w-25 text-center">
          <%= image_tag(op.product.photo, class:"command-slat-img") %>
        </div>

        <div class="command-slat-infos d-flex flex-grow-1 justify-content-between align-items-center">
          <div class="content-left d-flex-column justify-content-center">
            <div class="text-left"><b><%= op.product.name %></div></b>
            <div class="d-flex justify-content-around">
              <%= link_to "❌ Effacer", order_product_path(op), method: :delete %>
              Quantité: <%= op.quantity %>
            </div>

          </div>
          <div class="content-right">
            <b><%= op.price %></b>
          </div>
        </div>
      </div>
      <div class="line-bottom my-4"></div>
    <% end %>


  <div class="shopping-card-amount text-right my-4">Montant Total de votre commande &nbsp:&nbsp <b> <%= @order.amount %>
    <%= form_tag orders_path do %>
      <%= hidden_field_tag 'customer_id', current_user.id %>
      <%= submit_tag 'Commander', class: 'btn btn-primary' %>
    <% end %>
  </div> </b>



  </div>
</div>

app/views/order_products/update.html.erb
<h1>OrderProducts#update</h1>
<p>Find me in app/views/order_products/update.html.erb</p>

app/views/orders/index.html.erb
<h1 class="text-center title-home">Mes Commandes</h1>

<div class="container order-list">
  <% @orders.each_with_index do |order, index| %>
    <div class="order_title">
      <%= link_to order_path(order) do %>
          <i class="fas fa-angle-double-right"></i> Commande N° <%= index + 1 %> - <%= order.created_at.strftime("commandée le %m/%d/%Y") %>
      <% end %>
      <hr>
    </div>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="order-container">
    <h1 class="text-center title-home my-4">Votre Commande : payée </h1>
    <% @order_products.each_with_index do |op, index| %>
      <div class="command-slats d-flex">
        <div class="w-25 text-center">
          <%= image_tag(op.product.photo, class:"command-slat-img") %>
        </div>
        <div class="command-slat-infos d-flex flex-grow-1 justify-content-between align-items-center">
          <div class="content-left d-flex-column justify-content-center">
            <div class="text-left"><b><%= op.product.name %></div></b>
            <div class="d-flex justify-content-around">
              <%#= link_to "❌ Effacer", order_product_path(op), method: :delete %>
              Quantité: <%= op.quantity %>
            </div>

          </div>
          <div class="content-right">
            <b><%= op.price %></b>
          </div>

        </div>
        <hr>

      </div>
      <div class="line-bottom my-4"></div>
    <% end %>
    <hr>

    <div class="shopping-card-amount text-right">Montant Total de votre commande &nbsp:&nbsp <b> <%= @order.amount %></div> </b>
</div>
</div>

app/views/pages/home.html.erb
<%= image_tag("banner.jpg", class: "img-fluid mb-3") %>

<div class="text-center title-home my-4">Nos Produits</div>

<div class="row">
  <a id="products"></a>
    <% @products.each do |product| %>
      <%= render partial: "components/product", locals: {product: product}%>
    <% end %>
</div>

<div class="text-center title-home my-4">Nos Producteurs</div>

<div class="row">
  <a id="productors"></a>
  <% @productors.each do |productor| %>
    <%= render partial: "components/productor", locals: {productor: productor}%>
  <% end %>
</div>

app/views/payments/new.html.erb
<div class="container page_size">
  <div class="row">
    <div class="col-md-6 offset-md-3">
    <h3>Paiement sécurisé - MyPerigord</h3>
      <%= form_tag order_payments_path(@order) do %>
        <article>
          <label class="amount">
            <span>Montant de votre commande: <%= humanized_money_with_symbol(@order.amount) %></span>
          </label>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="pk_test_f5GH45bDCvLIqEOmFHRJkiRY"
          data-name="Ma Commande"
          data-email="<%= current_user.email %>"
          data-description="Votre commande du <%= @order.created_at %>"
          data-amount="<%= @order.amount_cents %>"
          data-currency="<%= @order.amount.currency %>" class="text-center"></script>

      <% end %>
    </div>
  </div>
</div>

app/views/productors/show.html.erb
<div class="banner" style= "background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url( <%= @productor.productor_banner %> ) center">
  <h1> <%= @productor.compagny %> </h1>

</div>

<div class="container">
  <div class="productor-presentation">

    <%= image_tag @productor.avatar, class: "productor-avatar" %>

    <div class="productor-quote">
      <i class="fas fa-quote-left mr-5" style="font-size: 35px"></i>
      <em><%= @productor.quote %> </em>
      <i class="fas fa-quote-right ml-5" style="font-size: 35px"></i>
    </div>

  </div>

  <div class="productor-infos d-flex">
    <div class="productor-description">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum aspernatur autem pariatur molestias quia, porro voluptates sit vero alias natus itaque eaque fuga et dolorum mollitia, quibusdam magni id quis! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda cumque, minima impedit ipsam modi ab qui quisquam cupiditate aspernatur facilis eius illum, temporibus, quibusdam saepe laudantium nulla labore obcaecati cum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates pariatur, optio recusandae eveniet tempora a natus provident, at officiis doloribus aperiam libero assumenda impedit ducimus sit, explicabo nemo nobis asperiores.</p>
    </div>

    <div class="productor-contact d-flex flex-column">
      <p> <%= @productor.compagny %> </p>
      <p> <%= @productor.first_name %> <%= @productor.last_name %> </p>
      <p> <%= @productor.address %> </p>
      <p> <%= @productor.phone %></p>
      <p> <%= @productor.email %></p>
    </div>
  </div>

  <div class="row">
  <a id="products"></a>
    <% @productor.products.each do |product| %>
      <%= render partial: "components/product_productor_show", locals: {product: product}%>
    <% end %>
  </div>

</div>

app/views/products/index.html.erb
<h1>Product#index</h1>
<p>Find me in app/views/product/index.html.erb</p>

<% @products.each do |product| %>
  <%= product.name %>
<% end %>

app/views/products/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-lg-8">
      <div class=" d-flex flex-column justify-content-center product-price">
        <div class="row">
          <div class="col-lg-6 text-center">
            <%= image_tag(@product.photo, class:"image_product_show")  %>
          </div>
          <div class="col-lg-6">
            <div class=" d-flex flex-column justify-content-center product-price">
              <div class="mb-2">
                <b><%= @product.name %></b>
              </div>
              <div class="mb-2">
                <%= @product.price %>€
              </div>

              <%= link_to order_products_path(@product, product_id: @product.id), :method => "post", remote: true, class: "buy" do %>
                  <i class="fas fa-cart-plus cart-style"></i>
              <% end %>


            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12 mt-3">
            <p> <%= @product.description %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4 text-center">
      <div class="background-color p-3">
        <%= link_to "", productor_path(@product.productor), class:"product-link" %>
        <a href="#" class="position-absolute"></a>
        <h1 class="productor">producteur</h1>
        <%= image_tag(@product.productor.avatar, class:"image-productor") %>
        <div class="my-2 d-flex justify-content-end align-items-center">
            <span class="productor-first-name text-right mr-1"><%= @product.productor.acting_as.first_name %></span> <b class="productor-last-name text-right"><%= @product.productor.acting_as.last_name %></b>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center line-top mt-5">
    <p class="my-4">Nos Autres produits</p>
  </div>

  <div class="row">
  <a id="products"></a>
    <% @product.productor.products.each do |product| %>
      <%= render partial: "components/product_productor_show", locals: {product: product}%>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <a href="#"><%= image_tag "paysriberacois.png" %></a>
  <div class="footer-copyright">
    Site sponsorisé par la Communauté de communes du pays Ribéracois
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="title text-center">
  <div class="mx-auto my-4">
    <h2 class="mt-2">MY PERIGORD</h2>
    <p>Les produits locaux de qualité</p>
  </div>
</div>

<div id="navbar" class="fixed">

  <a href="/" class="navbar-item navbar-link">ACCUEIL</a>
  <a href="/#products" class="navbar-item navbar-link">NOS PRODUITS</a>
  <a href="/#productors" class="navbar-item navbar-link">NOS PRODUCTEURS</a>

  <% unless user_signed_in? %>
     <%= link_to "SE CONNECTER", new_user_session_path, class: "navbar-item navbar-link"  %>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to "MES COMMANDES", orders_path, class: "navbar-item navbar-link"  %>
    <%= link_to order_products_path, class: "basket navbar-item navbar-link" do %>
      <i class="fas fa-shopping-basket"></i>
        <div class="count <%= "d-none" if current_order.order_products.count == 0%>">
          <p class="cart-number"><%= current_order.order_products.count %></p>
        </div>
    <% end %>
    <%= link_to 'Se deconnecter', destroy_user_session_path, method: :delete, class: "navbar-item navbar-link" %>
  <% end %>


</div>